version: "2"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    #  network_mode: host
    ports:
      - 2181:2181
    expose:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000000000


  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    mem_limit: 2000000000
    ports:
      - 9092:9092
    expose:
      - 9092
    depends_on:
      - zookeeper
    network_mode: host
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.23.239.126:9092
      KAFKA_ADVERTISED_HOST_NAME: 172.23.239.126
      KAFKA_ZOOKEEPER_CONNECT: 172.23.239.126:2181
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
    #     KAFKA_CREATE_TOPICS: “Topic1:1:3,Topic2:1:1:compact”
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

